name: CI

on:
  push:
    branches:
      - master
    paths:
      - catppuccin/**
  pull_request:
    branches:
      - master
    paths:
      - catppuccin/**

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup Luacheck
        run:
          luarocks install luacheck

      - name: Linting
        run: |
          luacheck catppuccin/
