name: Deploy Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  deploy-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup Bake
        run: |
          curl -LO https://github.com/hyperupcall/bake/raw/main/pkg/bin/bake
          chmod +x bake

      - name: Create release and upload to Luarocks
        env:
          LUAROCKS_API: "${{ secrets.LUAROCKS_API }}"
        run: |
          ./bake release "${GITHUB_REF_NAME#v}"
